# jekyll configuration

# Site settings
title: Blog do Fabrício
author: Fabrício Godoy
email: contato@fgodoy.me
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor C#, Java, Javascript e Go que procura sempre
  acompanhar o mercado que está em constante mutação.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fgodoy.me" # the base hostname & protocol for your site
twitter_username: skarllot
github_username:  skarllot
exclude: [Gemfile, Gemfile.lock, Rakefile]

google_analytics:
  account: UA-80191858-1

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 10

gems:
  - jekyll-asciidoc
  - pygments
  - jekyll-paginate

asciidoctor:
  attributes:
    - basedir=:docdir
    - idseparator=_
    - imagesdir=/images
    - source-highlighter=pygments
    - icons=font
    - pygments-css=style
    - hardbreaks!

# end of configuration
