# jekyll configuration

# Site settings
title: Blog do Fabrício
author: Fabrício Godoy
email: contato@fgodoy.me
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor C#, Java, Javascript e Go que procura sempre
  acompanhar o mercado que está em constante mutação.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fgodoy.me"
timezone: America/Sao_Paulo
exclude: [Gemfile, Gemfile.lock, Rakefile]

google_analytics: UA-80191858-1
disqus: fgodoy
twitter: skarllot
github: skarllot

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 10

gems:
  - jekyll-asciidoc
  - pygments
  - jekyll-paginate

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=pygments
    - icons=font
    - pygments-css=style
    - hardbreaks!

# end of configuration
