# jekyll configuration

# Site settings
title: Blog do Fabrício Godoy
author: Fabrício Godoy
email: skarllot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor C#, Java, Javascript e Go que procura sempre
  acompanhar o mercado que está em constante mutação.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fgodoy.me" # the base hostname & protocol for your site
twitter_username: skarllot
github_username:  skarllot

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 10

gems:
  - jekyll-asciidoc
  - pygments
  - jekyll-paginate

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=pygments
    - icons=font
    - pygments-css=style

# end of configuration
