# jekyll configuration

title: "Fabrício Godoy"
name: Fabrício Godoy
avatar: https://avatars2.githubusercontent.com/u/122178?v=3&s=460

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

# end of configuration
