---
layout: post
tags:
  - autoconf
  - automake
  - autoreconf
  - autoscan
  - autotools
  - make
categories:
  - Programação
title: Hello World com Autotools
excerpt: >
  Nesse post irei explicar como fazer um programa que exibe "Hello World!" no
  console configurado com Autotools.
---
= Hello World com Autotools
Fabrício Godoy <contato@fgodoy.me>
v1.0, 2009-05-24
:lang: pt-BR
:revdate: 2009-05-24 20:23:36+00:00
:author: Fabrício Godoy
:creator: Fabrício Godoy
:producer: Fabrício Godoy

Para quem não conhece o Autotools, as ferramentas do mesmo têm o principal
objetivo de fazer programas portáveis, possibilitando assim que o programa possa
ser compilado em qualquer ambiente.

Vou explicar como fazer um programa que exibe “Hello World!” no console
configurado com Autotools. Não vou me ater a detalhes, ficando a cargo do leitor
pesquisar detalhadamente sobre as ferramentas.

Para continuar você precisará ter instalado as seguintes ferramentas: make,
gcc-c++, autoconf e automake. Para Windows você precisará também do MinGW e do
MSYS.

Vamos ao projeto:

1. Primeiramente crie uma pasta para o projeto (_hello-world_ por exemplo).

2. Agora crie a pasta src (o nome é sua escolha), ela irá conter o código fonte
do projeto.

3. Crie o arquivo _main.cpp_ dentro da pasta _src_, como o código abaixo.
+
[source,cpp]
.main.cpp
----
#include <iostream>

int main()
{
    std::cout << "Hello World!" << std::endl;
    return 0;
}
----

4. Dentro da pasta raíz do projeto crie o arquivo _Makefile.am_, com o conteúdo
abaixo.
+
[source,make]
.Makefile.am
----
SUBDIRS = src
----
+
Os arquivos _Makefile.am_ têm instruções de compilação, mais especificamente,
instruções para o comando _make_.
+
No caso deste arquivo, ele indica que deve ser pesquisado o diretório src.

5. Agora crie outro arquivo _Makefile.am_ no diretório _src_, com o seguinte
conteúdo:
+
[source,make]
.Makefile.am
----
bin_PROGRAMS = hello-world

hello_world_SOURCES = main.cpp
----
+
A primeira linha indica quais são os nomes dos programa executáveis.
+
A segunda linha indica quais são os arquivos fontes do programa hello-world.
Observe que todos os caracteres não alfabéticos devem der substituídos por "_",
como em _hello_world_.

6. Agora precisamos criar o arquivo _configure.ac_ (no diretório raíz do
projeto, daqui em diante iremos trabalhar apenas no diretório raíz), que irá
conter as configurações do projeto, como nome, versão e dependências do projeto
entre outros.
+
Para criar um arquivo _configure.ac_ preliminar execute o comando abaixo.
+
[source,bash]
----
$ autoscan
----
+
Serão criados os arquivos _configure.scan_ e _configure.log_, sendo que o
configure.scan é o configure.ac preliminar e o configure.log contém os erros
encontrados.
+
Renomeie o arquivo _configure.scan_ para _configure.ac_. O arquivo
_configure.log_ pode ser excluído.

7. Modifique o arquivo configure.ac como abaixo.
+
[source,m4]
.configure.ac
----
#                                               -*- Autoconf -*-
# Process this file with autoconf to produce a configure script.

AC_PREREQ([2.54])
AC_INIT([Hello World], [0.1.0], [myemail@server.com], [hello-world])
AC_CONFIG_SRCDIR([src])
AC_CONFIG_HEADERS([config.h])
AM_INIT_AUTOMAKE([1.9 -Wall -Werror])

# Checks for programs.
AC_PROG_CXX

# Checks for libraries.

# Checks for header files.

# Checks for typedefs, structures, and compiler characteristics.

# Checks for library functions.

AC_CONFIG_FILES([Makefile
src/Makefile])
AC_OUTPUT
----
+
*AC_PREREQ*: A versão mínima necessária do autoconf, geralmente é a versão 2.54.
+
*AC_INIT*: Define o nome e versão do projeto, endereço para relatar erros e o
nome do pacote do projeto.
+
*AC_CONFIG_SRCDIR*: Define a pasta que contém o código fonte.
+
*AC_CONFIG_HEADERS*: Define o nome do arquivo de definições do projeto, é
recomendável deixar o padrão.
+
*AM_INIT_AUTOMAKE*: É necessário para fazer uso dos _Makefile.am_. Define a
versão mínima do _automake_ e as opções _-Wall_ e _-Werror_ definem
respectivamente que devem ser mostrados todos os alertas e que todos os alertas
devem ser tratados como erros.
+
*AC_PROG_CXX*: Verifica e exige o compilador C++ para o projeto.
+
*AC_CONFIG_FILES*: Define os locais dos arquivo _Makefile_ do projeto.
+
*AC_OUTPUT*: Macro que executa a saída do _autoconf_.

8. É necessário executar os comandos _aclocal_, _autoconf_, _autoheader_ e
_automake_ para gerar o script de configuração do projeto, mas para facilitar há
o comando _autoreconf_ que executa todos os comandos necessários.
+
Inicialmente iremos executar o comando abaixo para que os arquivos iniciais
necessários sejam criados.
+
[source,bash]
----
$ autoreconf --install
----
+
Serão criados vários arquivos, sendo que o arquivo _INSTALL_ contém instruções
de instalação e configuração e o arquivo _COPYING_ contém a licença do programa.
+
O automake exige os arquivos _NEWS_, _README_, _AUTHORS_ e _ChangeLog_.
Inicialmente crie-os vazios.
+
[source,bash]
----
$ touch NEWS README AUTHORS ChangeLog
----

9. Execute o comando _autoreconf_ e será gerado o script de configuração do
projeto novamente, agora sem erros com o  automake.

10. Execute o script _./configure_ para configurar o projeto.

11. Execute o comando _make_ para compilar o projeto.

12. Teste o executável do projeto:
+
[source,bash]
----
$ src/hello-world
----

13. Para criar um pacote do projeto execute o seguinte comando:
+
[source,bash]
----
$ make dist
----
+
E será criado um pacote distribuível para outros que queiram compilar o projeto.
+
Para que além de ser criado o pacote o mesmo seja testado, execute o seguinte
comando:
+
[source,bash]
----
$ make distcheck
----

Pronto, é isso.

Aqui só é mostrado o básico necessário para começar a usar o Autotools, as
possibilidades vão muito além destas explicadas.

O pacote final pode ser acessado neste link:
http://dl.getdropbox.com/u/1671797/Blog/hello-world-0.1.0.tar.gz

== Referências

* Manual do autoconf: http://www.gnu.org/software/autoconf/manual/index.html
* Manual do automake: http://www.gnu.org/software/automake/manual/index.html

